# Generated by Django 5.2.7 on 2026-02-04 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentmodel',
            old_name='DepartmentName',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='doctormodel',
            old_name='DoctorName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='doctormodel',
            old_name='Specialization',
            new_name='specialization',
        ),
        migrations.RenameField(
            model_name='patientmodel',
            old_name='Age',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='patientmodel',
            old_name='Gender',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='departmentmodel',
            name='DepartmentDescription',
        ),
        migrations.RemoveField(
            model_name='doctormodel',
            name='doctor_image',
        ),
        migrations.RemoveField(
            model_name='patientmodel',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='patientmodel',
            name='PatientName',
        ),
        migrations.RemoveField(
            model_name='patientmodel',
            name='email',
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.doctormodel'),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.patientmodel'),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.departmentmodel'),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.doctormodel'),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
